const express=require('express');const path=require('path');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const Database=require('better-sqlite3');
const app=express();const PORT=process.env.PORT||3000;const JWT_SECRET=process.env.JWT_SECRET||'CHANGE_THIS_SECRET_BEFORE_PRODUCTION';
const db=new Database(process.env.DB_FILE||path.join(__dirname,'hesabi.db'));db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS businesses(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT,email TEXT,vat TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,business_id INTEGER NOT NULL,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'owner',created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(business_id) REFERENCES businesses(id));CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,business_id INTEGER NOT NULL,type TEXT NOT NULL,number TEXT,date TEXT,party TEXT,payment TEXT,amount REAL NOT NULL DEFAULT 0,note TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(business_id) REFERENCES businesses(id));CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,business_id INTEGER NOT NULL,name TEXT NOT NULL,sku TEXT,qty REAL NOT NULL DEFAULT 0,price REAL NOT NULL DEFAULT 0,min_qty REAL NOT NULL DEFAULT 0,FOREIGN KEY(business_id) REFERENCES businesses(id));`);
app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'تسجيل الدخول مطلوب'});req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch(e){res.status(401).json({error:'جلسة الدخول غير صالحة'})}}
app.post('/api/register',(req,res)=>{const {businessName,name,email,password}=req.body||{};if(!businessName||!name||!email||!password||password.length<6)return res.status(400).json({error:'أكمل البيانات، وكلمة المرور 6 أحرف على الأقل'});try{const b=db.prepare('INSERT INTO businesses(name) VALUES(?)').run(businessName.trim());const hash=bcrypt.hashSync(password,10);const u=db.prepare('INSERT INTO users(business_id,name,email,password_hash,role) VALUES(?,?,?,?,?)').run(b.lastInsertRowid,name.trim(),email.toLowerCase().trim(),hash,'owner');const token=jwt.sign({id:u.lastInsertRowid,businessId:b.lastInsertRowid,name,role:'owner'},JWT_SECRET,{expiresIn:'7d'});res.json({token,user:{name,role:'owner'},business:{id:b.lastInsertRowid,name:businessName}})}catch(e){res.status(400).json({error:e.message.includes('UNIQUE')?'البريد الإلكتروني مستخدم مسبقاً':'تعذر إنشاء الحساب'})}});
app.post('/api/login',(req,res)=>{const {email,password}=req.body||{};const u=db.prepare('SELECT * FROM users WHERE email=?').get((email||'').toLowerCase().trim());if(!u||!bcrypt.compareSync(password||'',u.password_hash))return res.status(401).json({error:'البريد الإلكتروني أو كلمة المرور غير صحيحة'});const b=db.prepare('SELECT * FROM businesses WHERE id=?').get(u.business_id);const token=jwt.sign({id:u.id,businessId:u.business_id,name:u.name,role:u.role},JWT_SECRET,{expiresIn:'7d'});res.json({token,user:{name:u.name,role:u.role},business:b})});
app.get('/api/me',auth,(req,res)=>{res.json({user:req.user,business:db.prepare('SELECT * FROM businesses WHERE id=?').get(req.user.businessId)})});
app.get('/api/transactions',auth,(req,res)=>res.json(db.prepare('SELECT * FROM transactions WHERE business_id=? ORDER BY id DESC').all(req.user.businessId)));
app.post('/api/transactions',auth,(req,res)=>{const x=req.body||{};if(!['sale','purchase','expense'].includes(x.type))return res.status(400).json({error:'نوع العملية غير صحيح'});const r=db.prepare('INSERT INTO transactions(business_id,type,number,date,party,payment,amount,note) VALUES(?,?,?,?,?,?,?,?)').run(req.user.businessId,x.type,x.number||'',x.date||new Date().toISOString().slice(0,10),x.party||'',x.payment||'نقدي',Number(x.amount)||0,x.note||'');res.json(db.prepare('SELECT * FROM transactions WHERE id=?').get(r.lastInsertRowid))});
app.delete('/api/transactions/:id',auth,(req,res)=>{db.prepare('DELETE FROM transactions WHERE id=? AND business_id=?').run(req.params.id,req.user.businessId);res.json({ok:true})});
app.get('/api/products',auth,(req,res)=>res.json(db.prepare('SELECT * FROM products WHERE business_id=? ORDER BY id DESC').all(req.user.businessId)));
app.post('/api/products',auth,(req,res)=>{const x=req.body||{};if(!x.name)return res.status(400).json({error:'اسم المنتج مطلوب'});const r=db.prepare('INSERT INTO products(business_id,name,sku,qty,price,min_qty) VALUES(?,?,?,?,?,?)').run(req.user.businessId,x.name,x.sku||'',Number(x.qty)||0,Number(x.price)||0,Number(x.min_qty)||0);res.json(db.prepare('SELECT * FROM products WHERE id=?').get(r.lastInsertRowid))});
app.delete('/api/products/:id',auth,(req,res)=>{db.prepare('DELETE FROM products WHERE id=? AND business_id=?').run(req.params.id,req.user.businessId);res.json({ok:true})});
app.get('/api/dashboard',auth,(req,res)=>{const rows=db.prepare('SELECT type,COALESCE(SUM(amount),0) total FROM transactions WHERE business_id=? GROUP BY type').all(req.user.businessId);const o={sales:0,purchases:0,expenses:0};rows.forEach(r=>o[r.type+'s']=r.total);o.net=o.sales-o.purchases-o.expenses;o.products=db.prepare('SELECT COUNT(*) c FROM products WHERE business_id=?').get(req.user.businessId).c;o.lowStock=db.prepare('SELECT COUNT(*) c FROM products WHERE business_id=? AND qty<=min_qty').get(req.user.businessId).c;res.json(o)});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log('حِسابي يعمل على http://localhost:'+PORT));
